name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"
modifier: "Mahdi Hasan"
inputs:
  MY_NAME:
    description: "Who to greet Enter The Name"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
